# Generated by Django 5.2.5 on 2025-08-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitions.submission')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('competition', 'submission')},
            },
        ),
    ]
